server:
  port: 8000
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/greendb
    driver-class-name: org.mariadb.jdbc.Driver
    username: green
    password: green1234
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
  output:
    ansi:
      enabled: always

logging:
  level:
    root: DEBUG